version: '3'

services:
 
  strapi:
    image: strapi/strapi
    environment:
      DATABASE_CLIENT: postgres
      DATABASE_NAME: strapi_mastic_db
      DATABASE_HOST: postgres
      DATABASE_PORT: 5432
      DATABASE_USERNAME: strapi_mastic_db
      DATABASE_PASSWORD: A_dreina_877
    volumes:
      - ./api-mastic:/srv/app
      - ./api-mastic:/usr/share/nginx/html:ro
    ports:
      - '1337:1337'

  postgres:
    image: postgres
    environment:
      POSTGRES_USER: strapi_mastic_db
      POSTGRES_PASSWORD: A_dreina_877
    volumes:
      - dataDB:/var/lib/postgresql/data
    ports:
      - '5432:5432'
  
volumes:
  dataDB: